language: generic
sudo: required
services:
  - docker
env:
  - BUILD_DIR="/tmp/the-little-lisper"
before_install:
  - docker pull silex/emacs:26.1-dev
  - docker run -v "TRAVIS_BUILD_DIR":"$BUILD_DIR" silex/emacs:26.1-dev /bin/sh -c "cd $BUILD_DIR"
install:
  # Install project dependencies
  - docker run silex/emacs:26.1-dev /bin/sh -c "cask install"
script:
  # verify Emacs version
  - docker run silex/emacs:26.1-dev /bin/sh -c "emacs --version"
  # Run tests
  - docker run silex/emacs:26.1-dev /bin/sh -c "cask exec ert-runner"
