language: generic
sudo: required
services:
  - docker
before_script:
  - docker pull silex/emacs:26.1-dev
install:
  # Install project dependencies
  - cask install
script:
  # verify Emacs version
  - emacs --version
  # Run tests
  - cask exec ert-runner