language: generic
sudo: required
services:
  - docker
env:
  global:
    - BUILD_DIR=/the-little-lisper
    - DOCKER_IMAGE=silex/emacs:26.1-dev
before_install:
  - docker pull "${DOCKER_IMAGE}"
install:
  # Start docker container, mount volume and set working directory to build dir
  - docker run -v "$TRAVIS_BUILD_DIR":"${BUILD_DIR}"
               -w "${BUILD_DIR}" "${DOCKER_IMAGE}"
               /bin/bash -c "emacs --version"
  # Install project dependencies
  - docker run -v "$TRAVIS_BUILD_DIR":"${BUILD_DIR}"
               -w "${BUILD_DIR}" "${DOCKER_IMAGE}"
               /bin/bash -c "cask install"
script:
  # Run tests
  - docker run -v "$TRAVIS_BUILD_DIR":"${BUILD_DIR}"
               -w "${BUILD_DIR}" "${DOCKER_IMAGE}"
               /bin/bash -c "cask exec ert-runner"
