language: emacs-lisp
sudo: required
dist: trusty
env:
  - EMACS=emacs25
  - EMACS=emacs-snapshot
before_install:
  # Official PPA for Emacs Lisp
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -y
  # Install Emacs (according to $EMACS)
  - sudo apt-get install -y ${EMACS}
  # Install Cask
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  # Setup Cask
  # - export PATH="$HOME/.cask/bin:$PATH"
install:
  # Install your dependencies
  - cask install
script:
  # Run your tests
  - emacs --version
  - cask exec ert-runner
