version: 2
jobs:
  build:
    docker:
      - image: silex/emacs/26.1-dev
    steps:
      - checkout
      - run:
          name: Install project dependencies 
          command: cask install
      - run:
          name: Run tests
          command: cask exec ert-runner
