version: 2
jobs:
  build:
    docker:
      - image: flycheck/emacs-cask/26.1
    steps:
      - checkout
      - run:
          name: Install project dependencies 
          command: cask install
      - run:
          name: Run tests
          command: cask exec ert-runner
