version: 2
jobs:
  build:
    docker:
      - image: jare/spacemacs-circleci:latest
    steps:
      - checkout
      - run:
          name: Install Cask
          command: sudo apt-get -y python2.7 python-pip
      - run:
          name: Install Cask
          command: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - run:
          name: Setup Cask
          command: export PATH="$HOME/.cask/bin:$PATH"
      - run:
          name: Install project dependencies 
          command: cask install
      - run:
          name: Run tests
          command: cask exec ert-runner
